In [0]:
import tensorflow  as tf
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.layers import Input,Dense,SimpleRNN,Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam,SGD

In [0]:
N=3
T=10
D=3
K=2
X= np.random.randn(N,T,D)
print(X)

[[[-2.15993509  0.32639809  0.65989884]
  [ 0.21709787 -1.21078285 -2.73288009]
  [ 1.74912446 -1.34519393 -0.12412736]
  [ 1.40499351 -1.1648973   0.54654498]
  [ 1.52940471  0.07139355  1.08439314]
  [ 0.18518555 -0.24266841 -1.35522584]
  [ 0.09844458  0.94931406  1.27149913]
  [-0.61552058  0.57901331  0.35579495]
  [-0.94098049 -0.18268192 -0.5701799 ]
  [-1.96439798 -0.59489825 -0.29221341]]

 [[ 0.44662116 -0.8630048  -0.25534218]
  [-0.08216447  0.05142697 -0.37090561]
  [ 0.07620883  0.07250335  0.5398241 ]
  [ 1.01925379 -0.50494297 -1.27279406]
  [-1.76185636 -0.6523466   0.71419522]
  [ 0.08524251 -0.47478985  0.85644814]
  [ 0.08557756 -1.03344249 -0.5648453 ]
  [ 1.73585838 -1.47797076 -0.93761597]
  [ 1.09427657  0.30266854 -0.27871408]
  [ 0.95447844  1.29431368  0.42533389]]

 [[ 0.84075209 -2.52003985  0.51415255]
  [ 0.1281368  -1.26686159 -0.29934415]
  [ 0.51941756 -1.37913089 -1.23016047]
  [ 0.85319659 -1.21349916 -0.69081848]
  [ 1.30149293 -0.54155575  2.090739

In [0]:
M=5
i= Input(shape=(T,D))
x= SimpleRNN(M)(i)
x= Dense(K)(x)

model= Model(i,x)

In [0]:
Yhat= model.predict(X)
print(Yhat)

[[ 0.4109731   0.15476732]
 [-0.1572231  -0.19620991]
 [-1.4357537  -0.20747247]]


In [0]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.layers[1].get_weights()

[array([[ 0.28798133, -0.55309653, -0.66902983,  0.2595976 ,  0.7942863 ],
        [-0.04810387,  0.47461706, -0.56197095, -0.5589006 ,  0.35798556],
        [ 0.01822406,  0.4571069 , -0.2073927 ,  0.8223316 ,  0.29508716]],
       dtype=float32),
 array([[ 0.25893438,  0.1230474 ,  0.24338518,  0.89840657, -0.22680739],
        [-0.901738  , -0.2722408 , -0.0962845 ,  0.3216213 , -0.00651346],
        [-0.26375097,  0.58651066,  0.6073413 , -0.05181641,  0.46356493],
        [-0.18651694,  0.7420937 , -0.45373046, -0.03983663, -0.4550277 ],
        [-0.12437088, -0.12667508,  0.5972926 , -0.29181087, -0.7256537 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [0]:
a,b,c= model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

#output 1 is input to hidden
#output 2 is hidden to hidden
#output 3 is bias term(vector of length M)




(3, 5) (5, 5) (5,)


In [0]:
Wx,Wh,bh= model.layers[1].get_weights()
Wo,bo= model.layers[2].get_weights()


In [0]:
h_last= np.zeros(M)#initial hidden state
x= X[0]#one and only sample
yhats= [] #storing outputs

for t in range(T):
  h= np.tanh(x[t].dot(Wx) + h_last.dot(Wh) +bh)
  y= h.dot(Wo) + bo #output value in it
  yhats.append(y)

  h_last= h #assigning the h_last

  print(yhats[-1])


[0.79760823 0.11604517]
[ 0.07434355 -0.2324485 ]
[-2.01820143 -0.25648435]
[-2.49191272  0.10594964]
[-0.22022763 -0.27388739]
[0.28141858 0.50633807]
[ 0.58661466 -0.37296907]
[0.39000293 0.35932507]
[ 1.33834767 -0.00892721]
[0.41097324 0.15476727]
