In [0]:
import tensorflow  as tf
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.layers import Input,Dense,SimpleRNN,Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam,SGD

In [0]:
N=1
T=10
D=3
K=2
X= np.random.randn(N,T,D)

In [0]:
M=5
i= Input(shape=(T,D))
x= SimpleRNN(M)(i)
x= Dense(K)(x)

model= Model(i,x)


In [0]:
Yhat= model.predict(X)
print(Yhat)

[[ 0.27077913 -0.39613512]]


In [0]:
model.summary()

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_5 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.layers[1].get_weights()

[array([[-0.5290253 , -0.29331768, -0.1925776 ,  0.7745008 , -0.00535953],
        [-0.5856057 ,  0.70256037,  0.10567695,  0.28187102, -0.31406468],
        [ 0.25943285,  0.51415163,  0.46063203, -0.4420993 , -0.43403557]],
       dtype=float32),
 array([[ 0.582821  , -0.35688865, -0.38698047,  0.35085338, -0.50999814],
        [ 0.77305645,  0.50266886,  0.26722524, -0.09611201,  0.26279432],
        [ 0.05724257,  0.00962524,  0.07423404, -0.82129973, -0.5626606 ],
        [-0.23718287,  0.7830776 , -0.2613672 ,  0.26796898, -0.43636402],
        [-0.05631031, -0.08155591,  0.8396508 ,  0.34831563, -0.40477228]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [0]:
a,b,c= model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

#output 1 is input to hidden
#output 2 is hidden to hidden
#output 3 is bias term(vector of length M)




(3, 5) (5, 5) (5,)


In [0]:
Wx,Wh,bh= model.layers[1].get_weights()
Wo,bo= model.layers[2].get_weights()


In [0]:
h_last= np.zeros(M)#initial hidden state
x= X[0]#one and only sample
yhats= [] #storing outputs

for t in range(T):
  h= np.tanh(x[t].dot(Wx) + h_last.dot(Wh) +bh)
  y= h.dot(Wo) + bo #output value in it
  yhats.append(y)

  h_last= h #assigning the h_last

  print(yhats[-1])


[-0.0167395  -0.77172589]
[0.16682466 0.26109036]
[0.06576058 0.20724493]
[ 0.10494229 -0.25213204]
[0.05006102 0.79938134]
[0.19825981 0.13835425]
[ 0.01298768 -0.30649436]
[-0.13148797 -0.72869184]
[ 0.17695311 -0.24965481]
[ 0.27077922 -0.39613504]
